### ISSUE TITLE
`can't found 'bundle' command` pops up when using `asdf-ruby`

### ISSUE THREAD

**Issue by alexanderadam** [atlantismonk/vscode-rubygems#6]
Thank you for creating this extension.
I thought I might give it a try but I'm getting the error [`can't found 'bundle' command`](https://github.com/xxamxx/vscode-rubygems/blob/9bdbd38be8d8e37e6da9dad2a8668662d0a7cd6d/src/lib/ruby-bundle-handler.ts#L14).

I'm using [`asdf-ruby`](https://github.com/asdf-vm/asdf-ruby#asdf-ruby), hence my `bundle` binary is in `~/.asdf/shims/bundle` (respective `$(asdf where ruby)/bin/bundle`) so this might be the issue.

Would it be to support Ruby version manager like `asdf` without having to override the `ENV` variable?

**Comment by xxamxx** [comment]
we can provide a property of configuration for Ruby version manager and bundle, can you implement that?

**Comment by Shawnt2918304** [comment]
Was this issue ever addressed?

**Comment by shawncamthom** [comment]
> we can provide a property of configuration for Ruby version manager and bundle, can you implement that?

https://github.com/xxamxx/vscode-rubygems/pull/8

**Comment by xxamxx** [comment]
thanks for your contribution.
